version: '3.8'

services:
  backend:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - '8000:8000'
    env_file:
      - .env
    volumes:
      - .:/code
  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    env_file:
      - .env